server:
  port: 8000
spring:
  application:
      name: glmall-member
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.110:3306/glmall_ums?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.2.110
    port: 6379

  #服务追踪
  zipkin:
    base-url: http://192.168.2.110:9411/  #zipkin服务器地址
    #关闭服务发现，否则Spring Cloud 会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web   #设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1  #设置抽样采集率为100%。 默认为0.1，即10%


#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: '*'