server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    alicloud:
        access-key: your access-key
        secret-key: your secret-key
        #阿里云对象存储
        oss:
          endpoint: oss-cn-beijing.aliyuncs.com
          bucket: your bucket
        #阿里云第三方的短信服务
        sms:
          host: https://fesms.market.alicloudapi.com
          path: /sms/
          skin: 1
          sign: 1
          appcode: your AppCode

  application:
    name: glmall-third-party
  #服务追踪
  zipkin:
    base-url: http://192.168.2.110:9411/  #zipkin服务器地址
    #关闭服务发现，否则Spring Cloud 会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web   #设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1  #设置抽样采集率为100%。 默认为0.1，即10%


management:
  endpoints:
    web:
      exposure:
        include: '*'