server:
  port: 25000
spring:
  application:
    name: glmall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.2.110
    port: 5672
    virtual-host: /
  redis:
    host: 192.168.2.110
  session:
    store-type: redis
  thymeleaf:
    cache: false