server:
  port: 10000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.110:3306/glmall_pms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    #缓存
    cache: false
  #SpingCache 使用redis缓存
  cache:
    type: redis
    redis:
      #缓存超时时间
      time-to-live: 3600s
      #key-prefix: CACHE_
      #默认使用分区名作为key前缀
      use-key-prefix: true
      #是否缓存空值
      cache-null-values: true
  redis:
    host: 192.168.2.110
    port: 6379
  session:
    store-type: redis

  #服务追踪
  zipkin:
    base-url: http://192.168.2.110:9411/  #zipkin服务器地址
    #关闭服务发现，否则Spring Cloud 会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web   #设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1  #设置抽样采集率为100%。 默认为0.1，即10%

#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #全局逻辑删除规则
      logic-delete-value: 1     # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0  # 逻辑未删除值(默认为 0)


feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    com.luoben.glmall: info
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

#线程池自定义配置
glmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10



